### ISSUE TITLE
Trojan detected on Windows 10

### ISSUE THREAD

**Issue by githubpetef** [onlineth/Spotlight-Desktop#12]
Please can you explain why Windows 10 is reporting that the file SpotlightDesktop Launcher.lnk contains Trojan:Win32/Detplock ?

**Comment by githubpetef** [comment]
Just found the other issue with your reply [https://github.com/onlineth/Spotlight-Desktop/issues/9](url)

**Comment by onlineth** [comment]
Yep, I tried to submit a false positive report to Microsoft this morning so hopefully, those annoying alerts go away https://github.com/onlineth/Spotlight-Desktop/issues/9
