### ISSUE TITLE
Error - "Cannot find the registry informationof the Spotlight image location" on latest Win10 build

### ISSUE THREAD

**Issue by jane-scott** [onlineth/Spotlight-Desktop#13]
First, thanks for making such a great little app! I've used it since you first brought it out.

I just wiped and fresh-installed 2 different machines yesterday with the latest Windows 10, Home, x64, v1709, build 16299.125. I put Spotlight Desktop x64 on them straight away, and it looks like both are having identical issues (similar to the two currently open bugs - feel free to merge or mark as duplicate if needed).

Error:
![image](https://user-images.githubusercontent.com/36668343/37126600-d7fffcfe-22c5-11e8-81bc-6b39077402a9.png)

Build:
![image](https://user-images.githubusercontent.com/36668343/37126631-012b3706-22c6-11e8-8b0a-c1810ebb75dc.png)

Registry:
![image](https://user-images.githubusercontent.com/36668343/37126672-2dd0bb14-22c6-11e8-8a62-39665da6ff6d.png)

![image](https://user-images.githubusercontent.com/36668343/37126584-c4c186d0-22c5-11e8-84b3-baeb95cbbeda.png)

As a temporary workaround, I created the new string value ```LandscapeAssetPath``` directly under ```SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative\S-1-5-21-...``` with the same content as the ```landscapeImage``` key. Then I ran SpotlightDesktop Launcher again and the desktop background was replicated from the Lock Screen successfully.

Let me know if I can help debug further :)

**Comment by jane-scott** [comment]
No problem - thanks for the fast reply. And thanks again for making this app! It's brilliant.

**Comment by arischs** [comment]
I'm facing the same issue @jane-scott  can you guide me through the process?

**Comment by jane-scott** [comment]
@arischs, sure. I've spelled it out for you step by step. I would have created a reg file for you but the location involves your SID and other unique key names which won't be the same on both of our systems.

1) Hold Windows key + R. In the Run box, type "regedit" (without quotes) and press Enter. The Registry Editor should open.

2) In the Registry Editor window, navigate to this location: ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative```. 

3) Expand the subkey under ```Creative``` which corresponds to your own user account SID (which will start with ```S-1-5-2...```).  Underneath that, you'll see several more subkeys listed, named with random numbers (for example ```131653866780996657``` on mine - yours will be different). Expand the last subkey listed. Refer to the screenshot in my last post above for an example of what this looks like.

4) Under that last subkey, you should see a value called ```landscapeImage```. Double-click it to open this value, and copy the whole string in the Value Data field to the clipboard. (This string will look something like ```C:\Users\<username>\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets\add25f4e372d140450bbab2d4049bc7c26db90d9e2ef0ad9f3480c2bd21303c8```.)

5) Go back up one key level, to ```S-1-5-21...```. Create a new String value here (right click -> New -> String Value), and name the new key ```LandscapeAssetPath```. Double-click your new key to open it, and in the Value Data field, paste in the value from the clipboard.

6) Restart your computer. Spotlight Desktop should now be working.

If not, please post a screenshot of your Registry Editor window (at the location of the new ```LandscapeAssetPath``` key you created) and I'll help you troubleshoot.

**Comment by arischs** [comment]
Thanks @jane-scott lemme give i a try :)
