### ISSUE TITLE
Pulling old creative Spotlight Image

### ISSUE THREAD

**Issue by GGsparta** [onlineth/Spotlight-Desktop#14]
This app has been working very well for a long time, but since mid-February, I always get the same spotlight background desktop (what is not the case of the spotlight lock screen).
I noticed that if I put another desktop background and then I restart the software, I come back on the same February old background desktop.
Is it still working for you?
![capture d ecran 2018-03-12 19 31 55](https://user-images.githubusercontent.com/18697680/37305353-75c7a272-2634-11e8-8514-65b7625fd772.png)

**Comment by onlineth** [comment]
It seems to be working on my system just fine, could you take a look at this guide and maybe checkout where the image is being pulled from and where the current lock screen image is?

https://github.com/onlineth/Spotlight-Desktop/wiki/Spotlight-Known-Locations-in-Registry

**Comment by GGsparta** [comment]
Done! The file referred in the key 'landscapeImage' (picture below) corresponds to the background I actually have in the lockscreen spotlight...
![capture d ecran 2018-03-13 07 13 40](https://user-images.githubusercontent.com/18697680/37327443-9b8c3b32-2696-11e8-93f7-443894e4c132.png)

If it can help, I also found the old February:
![capture d ecran 2018-03-13 07 19 49](https://user-images.githubusercontent.com/18697680/37327635-716d060a-2697-11e8-9da7-b74c5c378871.png)

**Comment by GGsparta** [comment]
Is there something new?

**Comment by onlineth** [comment]
Currently under midterms, once I have time to review this, I will.

**Comment by onlineth** [comment]
Sorry to keep you waiting, a new version is in the works right now. I've got someone else on this project as well and once we have a beta ready to go, I'll send you a beta if you would like to test it and see if it solves your problem.

**Comment by GGsparta** [comment]
okay, thank you guys!

**Comment by onlineth** [comment]
@GGsparta A Pre-release is out, let me know if this fixes your issue,

https://github.com/onlineth/Spotlight-Desktop/releases/tag/2.0.0

**Comment by GGsparta** [comment]
Well, still giving me the old same background (even if i change)

**Comment by GGsparta** [comment]
![image](https://user-images.githubusercontent.com/18697680/38112366-05798c58-33a2-11e8-8527-fbc01877e6ba.png)

As you're telling me it can have something to do with the user's directory, please note that I'm using 2 hard drive (SSD+HHD), with OS on the first, and Documents on the second...

The picture "C:\Users\yoyo6\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets\4a07e1344d956b57b28d9923722cb8d480babce98a275eb830ab8ff1a8722189" is my old same background...

**Comment by onlineth** [comment]
Just to let you know, the script has no fucntionalty to change the registry so no worries there:)

So, are the Spotlight images still rotating? Are you on the latest release or on a preview build? It's a bit odd that they're not in that directory.

If you're feeling up to it and just want it to work, you can do the following, export the creative key (which will export the subkeys associated with it) and then remove those three sub keys (the longer keys just under the creative key). 
Again if you do this, export beforehand just to have a backup. From my testing, Windows only uses this for Spotlight images and gets rebuilt if it is not found. Forcing Windows to rebuild it may be the best option (although I'd love to know if there's yet another location).

If you are able to find of a different place in the registry, please let me know then I can add it to the script. Honestly, Windows has changed where it stores the spotlight image information two times already, maybe this is a third:/

**Comment by GGsparta** [comment]
Yes... searching a fourth location is what I has in mind when I looked for the actual background that I didn't find.
I wasn't so sure that remove the sub keys would force Windows to rebuild, but I'll try this tommorow (it's a bit late in France ^^').

**Comment by GGsparta** [comment]
I did what you told me, but after rebooting, nothing has been rebuilt by Windows (Creative empty key alone is remaining, with no sub-keys).
Is there something I'm missing?

**Comment by onlineth** [comment]
It's not instant, it might take time (however long it usually takes to switch to a new Spotlight image)

**Comment by GGsparta** [comment]
Ok, I'll let you know when there's something new ^^

**Comment by GGsparta** [comment]
YEAAAAAAAAAH IT'S WORKING!
Thank you guys, you rock! Nice support!
