### ISSUE TITLE
marked as trojan in windows defender 

### ISSUE THREAD

**Issue by achozex** [onlineth/Spotlight-Desktop#15]
i know its a false alarm, but windows defender marked it
![troj](https://user-images.githubusercontent.com/10247595/38165898-d3ad137e-3523-11e8-93cd-cbf5b2dc27e7.PNG)

**Comment by onlineth** [comment]
Yep, I'm getting a release out now, just finishing up the updater. Turns out I can submit these be reviewed by Microsoft and have them marked as a false positive.

But yes, I would never create a trojan/virus linked to my personal information lol

**Comment by onlineth** [comment]
The latest release has been submitted to Microsoft's Windows Defender false positive page so hopefully, these messages start to disappear.

As for the MSI package, it seems like that will always show the "This publisher is unknown" message. Not that they could, but it would be wonderful is Let's Encrypt added some sort of way they could provide code signing certificates for free, or at least for a cheaper price.
