### ISSUE TITLE
Showing different image - no more update

### ISSUE THREAD

**Issue by neomodd** [onlineth/Spotlight-Desktop#16]
Hey guys,

since a few days the software is not refreshing the wallpaper any more.
Also the recent wallpaper, is a picture of a few flamingos, which I have never seen before.

I am running the software on my win 10 laptop, version 1803.

Best regards

**Comment by onlineth** [comment]
Hi,

I'm running the same version on both my laptop and desktop. I don't seem to be experiencing the same issue you are. It would help though to see what's going on.

Are you using the latest version of this software (currently 2.0.1)?

If so, please check this guide and let me know where the flamingo picture is appearing and where your current lock screen wallpaper is as well - https://github.com/onlineth/Spotlight-Desktop/wiki/Spotlight-Known-Locations-in-Registry


Thanks,

Thomas

**Comment by neomodd** [comment]
Hell Thomas,

first of all thank you for your fast answer.

Yes I am using the latest version 2.0.1 right now.

Alright, I followed your link and checked the locations within the registry.
The first loacation in

1. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\

leads me me indeed to the picture shown as me current background, the flamingos.
But this is not the picture which is my current lockscreen.

The exact same goes for the second location in the registry and within the third is no creative folder.

**Comment by onlineth** [comment]
Hmm, alright you're going to have to then take a look at your images folder where spotlight saves them, find the image that is currently your lock screen wallpaper, take that file name and search for it in your registry.

To do so, check this guide out and let me know what you find - https://github.com/onlineth/Spotlight-Desktop/wiki/Backtrace-Spotlight-Image

**Comment by neomodd** [comment]
Okay, after doing so I could trace the file in this directory:

Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths

than a key called url2 was marked blue.

**Comment by onlineth** [comment]
Hmm, probably not the first one and the second one should be the current background image or at the very least, a historical background image. Are you sure you are searching for the image that is the current lock screen background image?

**Comment by neomodd** [comment]
Oups sorry, I was searching for my current wallpaper. I will do it again.

**Comment by onlineth** [comment]
Hmm, that's really really strange. Unless Microsoft has started saving those wallpapers elsewhere (which would be the first time I've heard of), it might be because something got misconfigured when Windows rotates the Spotlight image.

I would recommend the following, change the lock screen image to any random picture, restart your computer, change it back to the Windows Spotlight Image, and restart again.

Give your computer a few days, if the issue is still persistent, let me know. Has the Spotlight image still been changing or has it been stuck on the same image it has been on now? If the Spotlight image does change but the desktop wallpaper still has that issue, let me know and we can go from there.

**Comment by neomodd** [comment]
Okay I followed your recommendation.

I will keep you up to date!

**Comment by neomodd** [comment]
Quick update:

It seems like it works again now!
I just switched on my laptop and was happily surprised to see another beautiful wallpaper from my lockscreen :)

Thank you a lot for your support!

**Comment by onlineth** [comment]
Great to hear!
