### ISSUE TITLE
Doesn't appear in system tray

### ISSUE THREAD

**Issue by Darthagnon** [onlineth/Spotlight-Desktop#18]
Would it be possible for the program to appear in the system tray? As it currently stands, it does not appear in the system tray and I can see no method of controlling it. E.g. I like it's functionality, but would rather use it on an ad-hoc basis, disabling it, re-enabling it, etc. Currently, I must choose between having it installed and using it forever, or not.

Bug: I browsed to the file location and was able to open a second, invisible instance of the program. It does not limit itself to a single instance, allowing potentially multiple redundant, invisible-to-the-user instances to be opened. This could potentially be remedied by adding a system tray icon - at least, then, the user could see that multiple instances are open.

**Comment by onlineth** [comment]
Hmm, I do understand your point of being able to enable and disable it.

The main objective of this script was to make it as minimal and small as possible. Adding a GUI or even something that goes in the taskbar could annoy users (it would annoy me tbh). Now, if you want the control, an idea could be a small program that runs in the taskbar and via clicking on it - it would either stop the Spotlight Desktop process or start it depending on if it's already running.

Being that it is only set to run on login only and does not provide any desktop or start menu icon, I don't see how someone could run multiple instances of it (you can only log in once). I've been using this myself and occasionally check my task manager, I've never seen this application spawn multiple times. If this does become a problem, then I could add something to the script to exit immediately if another instance of itself is running. With the exception of manually running the program, have you ever seen this launch multiple times on log in?

**Comment by Darthagnon** [comment]
Never seen it launch multiple times at login; just happened to notice that it is possible to open it multiple times, by double-clicking the executable. As there is no tray widget, it remains running as multiple instances (I don't know what effect this has, other than filling RAM), with no indication or way to close it, other than via Task Manager/shutdown.
