### ISSUE TITLE
image is broken on one monitor in a multi-monitor setup

### ISSUE THREAD

**Issue by jonathanmajh** [onlineth/Spotlight-Desktop#24]
This is what my monitor setup looks like
![Capture](https://user-images.githubusercontent.com/4502543/64556687-f5992200-d30d-11e9-9c23-73ce0fac262a.PNG)
This is the broken image on the bottom monitor
![broken-image](https://user-images.githubusercontent.com/4502543/64556688-f5992200-d30d-11e9-869d-256cac74cf51.PNG)
This is what the spotlight image looks like
![actual-image](https://user-images.githubusercontent.com/4502543/64556690-f5992200-d30d-11e9-8c06-f0cf88141f2d.PNG)

I'm using Windows 10 1903 18362.207

The bottom monitor resolution is 1366 x 768 the rest are 1920 x 1080

Thanks

**Comment by jonathanmajh** [comment]
nvm, it fixed itself after I closed and restarted the app

**Comment by onlineth** [comment]
Sounds good, let me know if you run into any other issues
