### ISSUE TITLE
Deleting old pictures? 

### ISSUE THREAD

**Issue by Anton700** [onlineth/Spotlight-Desktop#25]
Hi,
as I am using Windows tablet with little space, is it possible that program deletes older images?

**Comment by onlineth** [comment]
Hello @Anton700, while this program does not handle managing images that Spotlight downloads, you have luck checking `%LOCALAPPDATA%\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets`.

I should mention that in my folder, with the oldest image being from July, the total size is a mere 10mb.

Try using [Tree File Size](https://www.jam-software.com/treesize_free/) for help with finding larger files/folders.
