### ISSUE TITLE
Not changing the wallpaper

### ISSUE THREAD

**Issue by italodeandra** [onlineth/Spotlight-Desktop#26]
But also not giving me any errors.

**Comment by onlineth** [comment]
Have you tried rebooting?

If you could follow this guide and let me know what turns up - https://github.com/onlineth/Spotlight-Desktop/wiki/Backtrace-Spotlight-Image

**Comment by italodeandra** [comment]
Yes, I also tried looking for whats up in the registry. I think it might be something unusual with my Windows 10. But I found an alternative that don't do the same thing but did satisfy me.

Thank you.

**Comment by Dhyfer1** [comment]
@italodeandra what alternative are you talking about?
