### ISSUE TITLE
async Task.Delay() instead of Thread.Sleep()

### ISSUE THREAD

**Issue by b9chris** [onlineth/Spotlight-Desktop#27]
Thanks so much for making this and making it open source! Really appreciated reading this code, it's nice to learn how OS-fiddling tasks like this are done.

Technically Thread.Sleep() hangs a thread while Task.Delay() fully releases resources until the next wake. It's pretty easy now to make the Main() method async in the latest .Net/C# so you can call Task.Delay() instead. If you want I can put the Pull Request together or you can just take a swing at making the change.

https://stackoverflow.com/questions/20082221/when-to-use-task-delay-when-to-use-thread-sleep

https://dotnettutorials.net/lesson/async-main-csharp/

**Comment by onlineth** [comment]
Hi @b9chris, thank you for checking that!  This project was my first time with C# so there are probably a few places that can be improved on!  

If you could make a PR, that would be excellent!  Thanks again for taking the time to check:)
