### ISSUE TITLE
Sorry for this off-topic issue 

### ISSUE THREAD

**Issue by Dhyfer1** [onlineth/Spotlight-Desktop#28]
![image](https://user-images.githubusercontent.com/50301201/203892720-73e6e603-2933-4877-aa28-c3751a8b621b.png)

About this image, what software or website did you use to create the comparison line in the center of the image?

**Comment by onlineth** [comment]
Hi @Dhyfer1, so I did this by finding a generic HTML slider implementation [similar to this one](https://www.cssscript.com/before-after-comparison-slider-touch/) with a couple of tweaks.  There are probably more efficient ways of doing this, but that's what I used at the time.

![image](https://user-images.githubusercontent.com/7810121/203896801-4efce0fc-5315-47d1-ae23-c8d7f67d2889.png)

**Comment by Dhyfer1** [comment]
Wow thank you very much! I think your link can help me. 

That's all.
