### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by worldsdream** [onlineth/Spotlight-Desktop#3]
Hi,

Is there an option to uninstall? I don't see it.. Thanks

**Comment by onlineth** [comment]
I have not created an uninstaller for it yet. To remove it,

1. Stop the process from running from the Task Manager

>    ![Stop from the Task Manager](https://i.imgur.com/iG0o8uC.png)

2. Then, delete the directory `%AppData%/SpotlightDesktop`

>    ![Delete all the files or the directory](https://i.imgur.com/gYHFsHC.png)

3. Finally, if you go to your start menu, click on the StartUp folder and delete the Spotlight-Desktop entry there

>    ![Delete the entry in the StartUp folder](https://cloud.githubusercontent.com/assets/7810121/26521664/8402a9f0-42b3-11e7-938b-f19978a7e345.png)

That's all there is to it, let me know if you need any more explanation on this.

**Comment by worldsdream** [comment]
That worked. Will you implent an uninstallation? Also why is there a desktop icon. Clicking it does nothing?

**Comment by onlineth** [comment]
In regard to the desktop icon, in case someone did not want it to startup with the computer, they could remove it from the startup folder and click that. Also, it manually forces the script to run (change the background).

As for the uninstaller, I need a decent (and free) install creator. I'll look into that later today.

**Comment by worldsdream** [comment]
Thanks for the fast reply. Keep it up!

**Comment by onlineth** [comment]
@worldsdream If you want, you can give the new installer a try.

https://github.com/onlineth/Spotlight-Desktop/releases/tag/1.2.1

Download `Spotlight_Desktop.msi`

It was built with Advanced Installer and provides uninstall support. Let me know if you run into any issues.

**Comment by worldsdream** [comment]
@onlineth It installed it and I could uninstall it. But there was no desktop icon? Is that what you intend to do?

**Comment by onlineth** [comment]
Yes, I removed the desktop icon, I can add the desktop icon back if you want. What do you mean it didn't uninstall for you? It uninstalled for me.

**Comment by worldsdream** [comment]
Please read what I said, I tested it and I could INSTALL it and I also did test the uninstall and I could UNINSTALL it perfectly. So all is working. 

It would be nice if you give us a checkmark option on the end if we want the desktop icon. 

Also on the install I get:
http://i.imgur.com/oYh2vff.png

**Comment by onlineth** [comment]
Oh, ok - my bad. I'll add a checkmark option. Here's the thing with using Advanced Installer. I have to choose the MSI option and can't build it as a regular executable without paying for a professional license. Being that I am using the MSI option, I believe I have to purchase a code signing certificate, [which can be very expensive, unfortunately](https://www.gogetssl.com/code-signing-certificates/).

Obviously, this is a safe program to use. All the code is on GitHub so you can manually compile if you are truly security conscientious. Also, I would never package a virus or anything harmful and then attach that to my name:-).

I'll see if there are any ways around that message, though, and I'll add a desktop icon option now.

**Comment by onlineth** [comment]
Hmm, it looks like I'm going to have to upgrade to get an optional desktop shortcut, I'll just add it by default.

**Comment by worldsdream** [comment]
I understand. Thanks for the fast interaction and I love your simple program. I am happy that I found it!

**Comment by onlineth** [comment]
Sure thing, I got sick of trying to find backgrounds so I figured something like this would do the job. Let me know if you want any changes or features.
