### ISSUE TITLE
Not working on Build 16288.1

### ISSUE THREAD

**Issue by onlineth** [onlineth/Spotlight-Desktop#5]
According to a user on a discussion about this software, this does not appear to be working on build 16288.1.

**Comment by unnatural** [comment]
To be more specific, no wallpaper shows after install. just black screen.  I tried to uninstall and install but nothing happened.

**Comment by onlineth** [comment]
Ok, so the issue is that the new build does not place the image path in the registry - at least not where it used to be. I don't have a pc with a Windows Preview build where can snoop around on where the image path is so I may have to wait until this update rolls out to create a fix:/

**Comment by Simonx22** [comment]
It also no longer works for me with the update 1709. "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Lock Screen\\Creative" contains the last image before the update. So it's no longer updating the key there. I found that it's updating the key in Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative\xyz" but "xyz" is containing stuff like my own ID, so it's not unique.

**Comment by onlineth** [comment]
@Simonx22 Perfect, the location of the key is what I've been waiting for. I'm going to be redesigning the script in C++ for added performance. When I get a build, I'll send it over to you. Are there multiple id's in that subkey?

**Comment by Simonx22** [comment]
@onlineth Under "Creative" there is a folder named by my SID and another folder with an unique ID, but I don't know what it is.

**Comment by onlineth** [comment]
@Simonx22 I got a Windows Insider build on my tablet and see the change as well. Nice job finding that path, I've got a pretty hefty class load but I'll see what I can get out over the next few days.

**Comment by onlineth** [comment]
@Simonx22 Good news (sort of), [here's a prerelease](https://github.com/onlineth/Spotlight-Desktop/releases/tag/1.3)

This is working on my tablet with the newer build and this computer with the stable build. I'm not sure though, about the dependencies and other stuff, it should work on your system as well. Mind giving it a shot?

Running SpotlightDesktop.exe will show a console with some information on where the image is and when it picks up a change to the Spotlight image and running SpotlightDesktop Launcher.exe will just hide the console window - just run the SpotlightDesktop.exe and that will say it all.

idk if I will port this over to C++. This was not as easy as it should've been. I'll post a reason why in a bit, lmk how it goes. Once I know it works on someone else's system, I'll package it up in the installer.

**Comment by onlineth** [comment]
@unnatural This should be the fix you've been waiting for as well.

**Comment by onlineth** [comment]
Hmm, hold off maybe a bit, I'm running into the same issue I've been having before. Accessing that registry location is almost being blocked. I can't access it using `winreg.QueryValueEx()` and I was able to access it using `subprocess.check_output("reg query "` but that's having issues now too.

**Comment by onlineth** [comment]
@Simonx22 Sorry if I'm spamming you with emails, when you run SpotlightDesktop.exe, do you see a message that says "Using old registry location"?

**Comment by mikenik4** [comment]
So I just tried it on Win10 Version 1709 (build 16299.19) and it updated image, but it's not the same one as on lock screen.
Console log:
> Breaked from Level 3
> Using old registry location
> Spotlight image location found: C:\Users\mikenik4\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets\9ba5be1be9041d0e6e166ea3762d4da70d8e88a724caff910c7c11c7f48f4439
> Desktop wallpaper changed
> Finished updating the current Spotlight image

**Comment by Simonx22** [comment]
@onlineth Sorry, I'm currently at work and I don't have 1709 here yet. I will try when I'm at home. (around ~3 hours)

**Comment by Simonx22** [comment]
@onlineth Looks like it's working for me.

> Spotlight image location found: C:\Users\Simon\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets\ef2207e400a679cf442dd11b39deb47b56589bdaa018ef20466de0d3e730d7f5
>
>
> Desktop wallpaper changed
Finished updating the current Spotlight image

**Comment by Simonx22** [comment]
@onlineth this was tested with my own computer at home. (Windows 10, version 1709)

**Comment by onlineth** [comment]
Sorry, mixed up you and @mikenik4

**Comment by onlineth** [comment]
I'm working on a fix. This update has just been awful for this application, but I see the finish line ahead:). There are *three* locations where it could be, and the one with the newest build is a little weird, hopefully by tonight, this can be closed.

**Comment by Simonx22** [comment]
@onlineth I'm pretty sure that you already know this, but Windows Defender doesn't like your application at all, they think it's a trojan iirc.

**Comment by onlineth** [comment]
I know @Simonx22 Norton and Defender has made me want to quit programming but one problem at a time:)

**Comment by Simonx22** [comment]
@onlineth yeah, just wanted to say. I really like your application, so keep up the good work. :)

**Comment by Simonx22** [comment]
@onlineth yeah, just wanted to say. I really like your application, so keep up the good work. :)

**Comment by onlineth** [comment]
@Simonx22 It appears that the Defender alerts come from not compiling for the right architecture (I wanted to use 32bit so I didn't have to worry about 64bit releases but those pop alerts probably a great welcome message for newcomers).

That's been fixed, let me know with this next build if you get those warnings again, I didn't on my tablet and I'm assuming you won't either. If you're using a 64bit system which from the warning I would assume you are (after all, who's still on 32bit these days), make sure to download the 64bit version.

**Comment by onlineth** [comment]
@mikenik4 This should fix your issue, let me know if it does. Below is (hopefully) the last build for 1.3 which should fix and close this issue.

https://github.com/onlineth/Spotlight-Desktop/releases/tag/1.3.2

**Comment by mikenik4** [comment]
@onlineth This works, cool.

**Comment by onlineth** [comment]
Thanks again @Simonx22 @mikenik4 & @unnatural - here's the release with the installer. https://github.com/onlineth/Spotlight-Desktop/releases

Turns out that, at least on my tablet, Windows Defender says Unkown Publisher when trying to launch this. Unfortunately, [code signing certificates are kind of expensive](https://www.gogetssl.com/code-signing-certificates/comodo-codesigning-ssl/) so we may have to live with that warning:/
